export const dbPlayers = [
  {
    id: 1,
    name: "Lionel Messi",
    club: "Inter Miami",
    nationality: "Argentina",
    position: "Forward",
    statistics: {
      overall: 93,
      pace: 80,
      shooting: 90,
      passing: 91,
      dribbling: 95,
      defending: 35,
      physical: 65,
    },
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    club: "Al Nassr",
    nationality: "Portugal",
    position: "Forward",
    statistics: {
      overall: 90,
      pace: 80,
      shooting: 93,
      passing: 81,
      dribbling: 87,
      defending: 35,
      physical: 78,
    },
  },
  {
    id: 3,
    name: "Kylian Mbappé",
    club: "Paris Saint-Germain",
    nationality: "France",
    position: "Forward",
    statistics: {
      overall: 91,
      pace: 97,
      shooting: 89,
      passing: 86,
      dribbling: 92,
      defending: 38,
      physical: 76,
    },
  },
  {
    id: 4,
    name: "Kevin De Bruyne",
    club: "Manchester City",
    nationality: "Belgium",
    position: "Midfielder",
    statistics: {
      overall: 91,
      pace: 75,
      shooting: 85,
      passing: 93,
      dribbling: 89,
      defending: 60,
      physical: 78,
    },
  },
  {
    id: 5,
    name: "Neymar Jr.",
    club: "Al-Hilal",
    nationality: "Brazil",
    position: "Forward",
    statistics: {
      overall: 89,
      pace: 86,
      shooting: 87,
      passing: 88,
      dribbling: 92,
      defending: 37,
      physical: 60,
    },
  },
  {
    id: 6,
    name: "Robert Lewandowski",
    club: "Barcelona",
    nationality: "Poland",
    position: "Forward",
    statistics: {
      overall: 91,
      pace: 82,
      shooting: 93,
      passing: 79,
      dribbling: 87,
      defending: 40,
      physical: 85,
    },
  },
  {
    id: 7,
    name: "Mohamed Salah",
    club: "Liverpool",
    nationality: "Egypt",
    position: "Forward",
    statistics: {
      overall: 90,
      pace: 92,
      shooting: 89,
      passing: 82,
      dribbling: 90,
      defending: 47,
      physical: 65,
    },
  },
  {
    id: 8,
    name: "Karim Benzema",
    club: "Al-Ittihad",
    nationality: "France",
    position: "Forward",
    statistics: {
      overall: 90,
      pace: 80,
      shooting: 92,
      passing: 84,
      dribbling: 88,
      defending: 40,
      physical: 78,
    },
  },
  {
    id: 9,
    name: "Virgil van Dijk",
    club: "Liverpool",
    nationality: "Netherlands",
    position: "Defender",
    statistics: {
      overall: 90,
      pace: 76,
      shooting: 60,
      passing: 76,
      dribbling: 65,
      defending: 91,
      physical: 87,
    },
  },
  {
    id: 10,
    name: "Kante N'Golo",
    club: "Al Ahli",
    nationality: "France",
    position: "Midfielder",
    statistics: {
      overall: 89,
      pace: 75,
      shooting: 70,
      passing: 80,
      dribbling: 75,
      defending: 90,
      physical: 78,
    },
  },
  {
    id: 11,
    name: "Alisson Becker",
    club: "Liverpool",
    nationality: "Brazil",
    position: "Goalkeeper",
    statistics: {
      overall: 90,
      pace: 50,
      shooting: 25,
      passing: 75,
      dribbling: 40,
      defending: 60,
      physical: 85,
    },
  },
  {
    id: 12,
    name: "Sadio Mané",
    club: "Al Nassr",
    nationality: "Senegal",
    position: "Forward",
    statistics: {
      overall: 89,
      pace: 90,
      shooting: 88,
      passing: 78,
      dribbling: 89,
      defending: 45,
      physical: 80,
    },
  },
  {
    id: 13,
    name: "Bruno Fernandes",
    club: "Manchester United",
    nationality: "Portugal",
    position: "Midfielder",
    statistics: {
      overall: 88,
      pace: 75,
      shooting: 86,
      passing: 90,
      dribbling: 87,
      defending: 50,
      physical: 70,
    },
  },
  {
    id: 14,
    name: "Harry Kane",
    club: "Bayern Munich",
    nationality: "England",
    position: "Forward",
    statistics: {
      overall: 90,
      pace: 78,
      shooting: 92,
      passing: 84,
      dribbling: 81,
      defending: 40,
      physical: 84,
    },
  },
  {
    id: 15,
    name: "Luka Modrić",
    club: "Real Madrid",
    nationality: "Croatia",
    position: "Midfielder",
    statistics: {
      overall: 88,
      pace: 70,
      shooting: 80,
      passing: 91,
      dribbling: 85,
      defending: 60,
      physical: 70,
    },
  },
  {
    id: 16,
    name: "Ruben Dias",
    club: "Manchester City",
    nationality: "Portugal",
    position: "Defender",
    statistics: {
      overall: 87,
      pace: 65,
      shooting: 60,
      passing: 75,
      dribbling: 60,
      defending: 88,
      physical: 85,
    },
  },
  {
    id: 17,
    name: "Gareth Bale",
    club: "Retired",
    nationality: "Wales",
    position: "Forward",
    statistics: {
      overall: 84,
      pace: 90,
      shooting: 85,
      passing: 78,
      dribbling: 87,
      defending: 40,
      physical: 70,
    },
  },
  {
    id: 18,
    name: "Son Heung-min",
    club: "Tottenham Hotspur",
    nationality: "South Korea",
    position: "Forward",
    statistics: {
      overall: 89,
      pace: 89,
      shooting: 87,
      passing: 80,
      dribbling: 88,
      defending: 40,
      physical: 75,
    },
  },
  {
    id: 19,
    name: "Jude Bellingham",
    club: "Real Madrid",
    nationality: "England",
    position: "Midfielder",
    statistics: {
      overall: 87,
      pace: 82,
      shooting: 81,
      passing: 86,
      dribbling: 90,
      defending: 60,
      physical: 75,
    },
  },
  {
    id: 20,
    name: "Marcus Rashford",
    club: "Manchester United",
    nationality: "England",
    position: "Forward",
    statistics: {
      overall: 85,
      pace: 91,
      shooting: 82,
      passing: 78,
      dribbling: 87,
      defending: 45,
      physical: 80,
    },
  },
];

export const dbClubs = [
  { id: 1, name: "Real Madrid", country: "Spain" },
  { id: 2, name: "Barcelona", country: "Spain" },
  { id: 3, name: "Manchester United", country: "England" },
  { id: 4, name: "Bayern Munich", country: "Germany" },
  { id: 5, name: "Liverpool", country: "England" },
  { id: 6, name: "Juventus", country: "Italy" },
  { id: 7, name: "Paris Saint-Germain", country: "France" },
  { id: 8, name: "Chelsea", country: "England" },
  { id: 9, name: "Manchester City", country: "England" },
  { id: 10, name: "AC Milan", country: "Italy" },
  { id: 11, name: "Inter Milan", country: "Italy" },
  { id: 12, name: "Arsenal", country: "England" },
  { id: 13, name: "Atlético Madrid", country: "Spain" },
  { id: 14, name: "Borussia Dortmund", country: "Germany" },
  { id: 15, name: "Tottenham Hotspur", country: "England" },
  { id: 16, name: "AS Roma", country: "Italy" },
  { id: 17, name: "Napoli", country: "Italy" },
  { id: 18, name: "Benfica", country: "Portugal" },
  { id: 19, name: "Ajax", country: "Netherlands" },
  { id: 20, name: "FC Porto", country: "Portugal" },
];
